### ISSUE TITLE
registration failure - 504 Gateway timeout

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#112]
at 5:33am or so, I attempted to submit a two-person registration for the event "Hallets Cove Morning Outfitting Trip" for May 31.

It spun for a while, then came back with a 504 Timeout after 30s-1min of waiting

When I used the browser back button, my registrant info was there, but the information for the additional participant was gone, so I added them again, with the same result
![image](https://user-images.githubusercontent.com/11206022/79684599-c7af8080-8200-11ea-9f2c-c8519da4f8c2.png)

**Comment by davidem00** [comment]
I'll venture a guess that it's choking on the empty contact fields.  Will fill it them out and try again

**Comment by davidem00** [comment]
Nope, even providing missing info, still failed:

![image](https://user-images.githubusercontent.com/11206022/79684750-cb8fd280-8201-11ea-89f3-b0a9aedcae59.png)

**Comment by davidem00** [comment]
I finally tried removing the additional member altogether, and had the same result

**Comment by davidem00** [comment]
I restarted from the beginning of the form, and still failing.  Environmental issues should be reflected back in the error to the user, even if ugly.

**Comment by davidem00** [comment]
I see in the Participants list that the first member of my party went in the first time (5:35am), but it failed to insert the second person.

No evidence of the subsequent attempts, as now all of the additional attempts I made to add people have failed, even solo participants.

**Comment by PoLoMoTo** [comment]
Fixed by #134
