### ISSUE TITLE
error 504 Gateway Timeout failures need more error info returned

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#113]
the server should be returning some kind of information about the failure, even if it's cryptic, to give a user a fighting chance

**Comment by davidem00** [comment]
related to #112

**Comment by PoLoMoTo** [comment]
504 errors are returned by Nginx, not Node, therefore no more information can be provided with them.  The errors will have to be handled in Node.

**Comment by davidem00** [comment]
can a mechanism be put in place to have the server/Node respond with something other than a timeout when it encounters an "unhandled" exception (one for which you don't want other specific handling)?

I'm not familiar with returning the various HTTP error codes, so wouldn't know if there is a "usual" one to use indicate a general catch-all system problem which is explicitly returned, telling the browser there was an error, but _also_ allows the server to give back information (as opposed to ones putting up custom error pages for specific errors, which are fine when you want to construct them).

I see that a generic 500 error code exists, but can't tell if it allows for returning extended information from the server, as something like 510 or 511 seem to allow.
