### ISSUE TITLE
registration form additional party member numbering should start at '2'

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#114]
the registrant is implicitly the 1st member of the party (not the zeroth :) )

![image](https://user-images.githubusercontent.com/11206022/79684875-9d5ec280-8202-11ea-958a-67f5e8127809.png)

**Comment by davidem00** [comment]
should also just remove the redundant label prefixes, the sectioning is obvious.  Make the entry fields themselves wider so they don't clip the input values

**Comment by PoLoMoTo** [comment]
Addressed by #134
