### ISSUE TITLE
incomplete registration insertion - partial insertion only

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#117]
a registration should either succeed completely or fail completely

See  #112 

I submitted a registration for a party of two, but only one made it into the system.

https://test.polomoto.com/event/27f40486-bf13-4916-83dc-f3ff756c515a

![image](https://user-images.githubusercontent.com/11206022/79685637-3e03b100-8208-11ea-84f9-1b001da11a63.png)

**Comment by davidem00** [comment]
I'm not familiar with your table structure, but if you are not using SQL transactions to perform your inserts for a single registration, you can often achieve this by orphaning the child records if the master record fails to insert.  If you insert the child records first (each participant) marked with the appropriate id you intend to use (the guid you've created), then you only proceed to insert the master record with the same guid once all of the child record inserts have succeeded.  If the master record fails to be created, you just have some orphans that don't matter, and are effectively invisible to the application.

This is another related reason (besides what we talked about with data restores) why foreign keys are shitty.  You can't do this if you are using foreign keys.

**Comment by PoLoMoTo** [comment]
Fixed by #134
