### ISSUE TITLE
new redundant Emergency Contact Phone field added to registrant/participant fields

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#131]
it lists both "Emergency Contact Phone Number" and "Registrant Emergency Contact Phone Number"

Somehow both are required.

![image](https://user-images.githubusercontent.com/11206022/80251303-68f46780-8643-11ea-9ef6-78d8680ce48b.png)

**Comment by PoLoMoTo** [comment]
Fixed by #134
