### ISSUE TITLE
event definition screen truncates existing name upon edit and save

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#73]
fields should not be truncating existing values, should scroll, and need more room in general.  Names can be long
The entry field for this can could probably be a "full" width field, taking up the space of two columns of fields in the current entry form.  Look back in our calendar for relevant event titles to see how long they can be

**Comment by PoLoMoTo** [comment]
Could you elaborate on what you mean by truncating and provide screenshots if possible?

**Comment by davidem00** [comment]
The one currently listed as "Annual" was originally given the name Annual Winter Trip when created, and showed as such in the grid.  Then I edited it to increase the party size, and when it saved, it truncated the name to "Annual" because that is all that fit in the Edit field

**Comment by davidem00** [comment]
(1) the edit field for Event Name (as well as Notes, and Description) are too small.
(2) they cannot truncate their existing values

**Comment by PoLoMoTo** [comment]
Fixed by #186
