### ISSUE TITLE
event definition fields Notes and Description need to be larger and scrollable

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#76]
people won't be able to edit values through a keyhole

**Comment by davidem00** [comment]
if something's not usable the way it is, "it's a bug"

**Comment by PoLoMoTo** [comment]
You _can_ use it though, you _can_ look through a pinhole

**Comment by davidem00** [comment]
a user is not going to be able to effectively use it if they can't read a whole sentence or even a phrase.

**Comment by PoLoMoTo** [comment]
It is an enhancement.

**Comment by PoLoMoTo** [comment]
Addressed by #186
