### ISSUE TITLE
all date/time displays in implicit "local" timezone (like in Registrant event selection)

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#85]
It should be in the Timezone where the event will take place, so is implicit (in terms of display)

no user, especially registrants, should be presented with "Fri Jul 10 2020 12:00:00 GMT+0000 (Coordinated Universal Time)" like in the event selection menu on the registration pages

This can be taken from some server config if that easiest to deal with, but ideally should be an explicit config for the application

**Comment by davidem00** [comment]
![image](https://user-images.githubusercontent.com/11206022/79680443-a38e7800-81dd-11ea-8665-e70ada83fa1f.png)

**Comment by PoLoMoTo** [comment]
Addressed by #134

**Comment by davidem00** [comment]
This needs to be handled comprehensively in the system

The Registration time is still being given in UCT, e.g.

The three shown registrations were made at 4:14am (for matter and fatika party) and 4:05pm for yoyo ma.
![image](https://user-images.githubusercontent.com/11206022/80289922-ebe2f400-870f-11ea-933a-34fba6daa074.png)

**Comment by davidem00** [comment]
Registration Time from the manual Selections page
![image](https://user-images.githubusercontent.com/11206022/80301980-5bd79580-8775-11ea-9bba-e6a5b653e9e4.png)

**Comment by davidem00** [comment]
as an aside, you could apply an appropriate TZ indicator to technical activity like "DB actions" e.g., like Registration Time, but in the appropriate local TZ of the current user, as these timestamps are not things that are intrinsically tied to a locale, as are things like begin/end times for a specific event, but we'll do everything in short/implicit local time for consistency.

In global systems, some timestamps are translated to local time from a UCT time stored in a db, while other "times of day" are invariant, always showing the same time of day "untranslated" irrespective of the location of the user, and still others are left in UCT.  All within the same system, intentionally, depending upon the purpose for which the time is recorded.  Sometimes "today" or the current "business day" has meaning shifted differently from the proper calendar day in each locale.  Date treatments can get very complicated depending upon business rules, and are ripe for mistakes when translating them.

**Comment by PoLoMoTo** [comment]
This is caused because the test database is running in a docker container which defaults to GMT, should not occur on the beta server.
