### ISSUE TITLE
time entry and display must be in "system" timezone

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#86]
right now it is accepting and displaying as UCT everywhere (see event signup event selection page)

it's fine to leave the DB storage in UCT, but you have to convert everywhere the user encounters it

**Comment by davidem00** [comment]
![image](https://user-images.githubusercontent.com/11206022/79680466-d6387080-81dd-11ea-8036-1447f555fff5.png)

**Comment by davidem00** [comment]
Timezone handling is a tricky item in many systems (whether to store in UCT or "local" time, vs needs for input/display conversion), and hard to get right.  Fortunately, this system will effectively only be interacted with by users in a single timezone.

However, someone registering for an event if while they are in California should not be shown the time of an event converted to their local timezone.  It should display in the "system" timezone (and not necessarily where the server is being run, because then you might have issues with differences between where the DB server, app server, browser are being run.  Again, it gets tricky.

**Comment by PoLoMoTo** [comment]
This is caused because the test database is running in a docker container which defaults to GMT, should not occur on the beta server.

**Comment by davidem00** [comment]
Understood.
It's fine for this system because of the nature of the deployment and the "single zone" usage, but it's worth appreciating that one must often separate the notion of the "system timezone" of where the various servers or clients are running from a global notion of a "system timezone" for a distributed system as a whole that may run on multiple servers in multiple timezones.
The later must typically be explicit within the software itself, and divorced from the system timezone of the various hosts, due to the need to host such servers around the world for performance, bandwidth and failover/redundancy requirements.  You cannot really rely on the hosting physical location and the particulars of the provisioning system to meet your needs.
