### ISSUE TITLE
Registration Volunteer Y/N signup button label should say "Continue Registration"

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#88]
At the prompt for the registrant to indicate whether they are signing up as a volunteer or not, the button says "Submit Registration", but it "Submit" is properly for the end of the process, not the beginning

![image](https://user-images.githubusercontent.com/11206022/79679300-c23b4180-81d2-11ea-94b6-1f284e9137ca.png)

**Comment by PoLoMoTo** [comment]
Addressed by #134
